#+title: orgroamtools 📓🔬

[[file:viz/COVER.svg]]

=orgroamtools= is a Python library to assist in data analysis of =org-roam= collection.
To use it, all you need is a healthy =org-roam v2= database!
Before getting started, take a minute to locate the database by checking the value of =(org-roam-db-location)= (Do this with =C-h v org-roam-db-location=), then make sure it is up to date by running =(org-roam-db-sync)=.

*Note:* Though =org-roam= allows different nodes with the same title, it is HIGHLY recommended that the notes in your collection have unique titles.
For better ergonomics, it is possible to retrieve nodes out of your =RoamGraph= by title.
This library will not stop you from persisting with duplicated titles, but you will be warned whenever the ambiguity might prevent desired behavior.

* Getting Started
Install the library in a virtual environment if desired:
#+begin_src sh
python -m pip install orgroamtools
#+end_src
Import the library and pass in your database path:
#+begin_src python
from orgroamtools.data import RoamGraph
collection = RoamGraph(PATH_TO_ORG_ROAM_DB)
#+end_src

Documentation and features for the library can be read [[https://aatmunbaxi.github.io/orgroamtools][here]].
* Dependencies
- Python 3.10+
- =networkx=: a graph analysis library for Python
- =orgparse=: a Python library for parsing =org-mode= files
* Related
- =obsidiantools=
